#!/usr/bin/env ruby

# Prepares for in-repo execution.
if File.exist?(File.expand_path("../../.git", __FILE__))
	$:.unshift(File.expand_path("../../lib", __FILE__))
	ENV["BUNDLE_GEMFILE"] = File.expand_path("../../Gemfile", __FILE__)
end

require "bundler/setup"
require "generous"
require "generous/legacy/run"
